version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies"
      - npm install

  build:
    commands:
      - echo "Building React app"
      - npm run build

  post_build:
    commands:
      - echo "Deploying React app to EC2 via SSM"
      - |
        aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --targets '[{"Key":"tag:Name","Values":["frontend-public-ec2"]}]' \
          --comment "Deploy React frontend" \
          --parameters '{"commands":["sudo rm -rf /var/www/html/*","sudo cp -r $CODEBUILD_SRC_DIR/build/* /var/www/html/","sudo systemctl restart nginx"]}'

artifacts:
  files:
    - '**/*'
