version: 0.2

# Build frontend artifacts and upload to S3
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing frontend dependencies"
  pre_build:
    commands:
      - cd "$SOURCE_DIR"
      - npm ci
  build:
    commands:
      - npm run build --if-present
  post_build:
    commands:
      - VERSION="${CODEBUILD_RESOLVED_SOURCE_VERSION:0:7}"
      - ARTIFACT_KEY="$APP_NAME/$ENV/$VERSION.tar.gz"
      - echo "Packaging frontend artifact"
      - |
        if [ -d build ]; then
          tar -czf frontend.tar.gz build
        elif [ -d dist ]; then
          tar -czf frontend.tar.gz dist
        else
          tar -czf frontend.tar.gz .
        fi
      - echo "Uploading frontend artifact to S3"
      - aws s3 cp frontend.tar.gz "s3://$ARTIFACT_BUCKET/$ARTIFACT_KEY"
      - aws s3 cp frontend.tar.gz "s3://$ARTIFACT_BUCKET/$APP_NAME/$ENV/latest.tar.gz"
      - echo "$ARTIFACT_KEY" > artifact_key.txt
artifacts:
  files:
    - frontend.tar.gz
    - artifact_key.txt
